AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Topic Bulletin Sample SAM Template for topic-bulletin
Globals:
  Function:
    Timeout: 6
Resources:
  BulletinAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://l2l/c848da50bc136477bba836ddd0670b25
      Handler: app.lambda_handler
      Runtime: nodejs8.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  DispatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://l2l/c848da50bc136477bba836ddd0670b25
      Handler: dispatcher.lambda_handler
      Runtime: nodejs8.10
      Events:
        PubEventDispatch:
          Type: SNS
          Properties:
            Topic: arn:aws-cn:sns:cn-northwest-1:148543509440:context-sharing-output-channel
            FilterPolicy:
              event_type:
              - dispatch
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://l2l/c848da50bc136477bba836ddd0670b25
      Handler: register.lambda_handler
      Runtime: nodejs8.10
      Events:
        SubEventDispatch:
          Type: SNS
          Properties:
            Topic: arn:aws-cn:sns:cn-northwest-1:148543509440:context-sharing-output-channel
            FilterPolicy:
              event_type:
              - registration
  PutCoordinationServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://l2l/9fbe6d55fd5414a53e5caf25ce3b0733
      Handler: decision-making-util.putItem
      Runtime: nodejs8.10
      Events:
        PutCoordinationService:
          Type: Api
          Properties:
            Path: /coordination-services
            Method: put
  PutCollaborationItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://l2l/92682d59dc765ca98ced73599bcf8646
      Handler: collaboration-network-util.putItem
      Runtime: nodejs8.10
      Events:
        PutCoordinationService:
          Type: Api
          Properties:
            Path: /collaboraion
            Method: put
  PutIVEItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://l2l/48675dc3e6542ea70953892d4b0dae85
      Handler: ive-util.putItem
      Runtime: nodejs8.10
      Events:
        PutCoordinationService:
          Type: Api
          Properties:
            Path: /ive
            Method: put
