AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Topic Bulletin Sample SAM Template for topic-bulletin
Globals:
  Function:
    Timeout: 6
Resources:
  BulletinAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://l2l/fdc3aa0ca27682883ed2f1403508a602
      Handler: app.lambda_handler
      Runtime: nodejs8.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  DispatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://l2l/fdc3aa0ca27682883ed2f1403508a602
      Handler: dispatcher.lambda_handler
      Runtime: nodejs8.10
      Events:
        PubEventDispatch:
          Type: SNS
          Properties:
            Topic: arn:aws-cn:sns:cn-northwest-1:148543509440:context-sharing-output-channel
            FilterPolicy:
              event_type:
              - dispatch
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://l2l/fdc3aa0ca27682883ed2f1403508a602
      Handler: register.lambda_handler
      Runtime: nodejs8.10
      Events:
        SubEventDispatch:
          Type: SNS
          Properties:
            Topic: arn:aws-cn:sns:cn-northwest-1:148543509440:context-sharing-output-channel
            FilterPolicy:
              event_type:
              - registration
