application:
  name: Topic Bulletin
  db_tables:
    - coordination_services:
        name: coordination-services
    - coordinators:
        name: coordinators
    - participants:
        name: participants
    - pub_topics:
        name: pub-topics
    - sub_topics:
        name: sub-topics
    - collaboration:
        name: collaboration